# Configurations
markdown: kramdown
markdown_ext:  markdown,mkdown,mkdn,mkd,md
highlighter: rouge

# Needed for backward compatibility
gems: [jekyll-paginate]

# Permalinks
permalink:        /blog/:year/:month/:day/:title

# Setup
title:            'Rupesh Dabbir'
tagline:          'Engineer by Profession and Photographer by passion. JavaScript Enthusiast!'
description:      'SMALL things make big IMPACT!'
url:              'https://rupeshdabbir.github.io'
baseurl:          ''

# Navigation
navigation:
- text: About
  url: /about/
- text: Resume
  url: /resume/
- text: Blog
  url: /blog/
- text: Tags
  url: /tags/
- text: Archive
  url : /archive/
- text: Search
  url: /search/


# Author Details
author:         'Rupesh Dabbir'

#Social Media links (Use complete URL except for email)
dribbble:
email:
facebook:       'https://www.facebook.com/rupeshdabbir'
flickr:
github:         'https://github.com/rupeshdabbir'
gplus:          'https://google.com'
instagram:
pinterest:
linkedin:       'https://linkedin.com/in/rdabbir/'
rss:
stackoverflow:  'https://stackoverflow.com/users/1625557/technocorner'
twitter:        'https://twitter.com/whoisrupesh'

# Google Analytics
gahandler: 'UA-52149651-1'

#if footersvg is 'true' the social media links will be shown top on the copy right in the footer
footersvg: 'true'

# Disqus
disqushandler: 'testingblogo'

# txtpen
txtpenhandler: 'testingblogo'

# Blog Configurations
paginate: 10 # Posts per page on the blog index
paginate_path: '/blog/page:num'
destination: ./_site

# Custom vars
version:          0.9x beta 2
